### ISSUE TITLE
Improve error / exception handling with regards to cards

### ISSUE THREAD

**Issue by bytemask** [IllusionMods/KKManager#97] opened 2022-11-29 15:01 UTC
This may get rolled into turning card handling itself into a separate library (!) but it would be ideal if we can improve card handling so it doesn't crash the application. I've seen that malformed cards can easily crash kkmanager, and it leaves our users quite confused and confounded-

Could optionally seek to move problematic cards into another directory in general, or triage them for another helper application that can repair or resolve broken dependencies. Lots of options here, input is appreciated <3

**Comment by ManlyMarco** [comment] 2022-12-15 08:51
Can you give some examples of cards that crash the application? I can't reproduce the issue.

**Comment by ManlyMarco** [comment] 2023-02-03 00:25
Closing the issuse since I could not reproduce it myself and no one provided steps to reproduce.

**Closed by ManlyMarco** 2023-02-03 00:25 UTC
Labels: bug
