### ISSUE TITLE
P2P wants to download files I already have and delete files that should be kept (issue with disabled zipmods)

### ISSUE THREAD

**Issue by 0neW0rld** [IllusionMods/KKManager#109] opened 2023-02-08 01:55 UTC
KKManager v0.21.0 w/ P2P enabled

Everytime I run the updater the list of mods-to-download includes a bunch that I already have (black text instead of green) and it wants to delete some that should be kept (they can be found on the betterrepack site). Even if I go through with the download, when I run the updater again it will still list the same mods-to-download. I've also tried deleting the listed mods-to-download them from scratch but that doesn't fix the issue either.

Here's a screenshot (you can see that [HS2]coat.zipmod is listed for deletion, but that same mod can be found on the betterrepack site right now): ![image](https://user-images.githubusercontent.com/120766951/217405605-04462009-8515-423b-a045-87a67dfc2661.png)

**Comment by ManlyMarco** [comment] 2023-02-08 02:44
Does this only affect bleeding edge? Send the kkmanager.log file.

**Comment by 0neW0rld** [comment] 2023-02-08 14:19
> Does this only affect bleeding edge? Send the kkmanager.log file, preferably on discord.

No, it's not just bleeding edge, same thing happens with regular modpack as well. I sent you my log file on discord.

**Comment by ManlyMarco** [comment] 2023-02-08 14:37
Most likely caused by disabling zipmods in kkmanager. I'll look into fixing it for the next release after 0.21.1.

**Comment by yarrmateys** [comment] 2023-02-10 14:38
21.1 seems to have made this issue worse for me. now every time i enable it it wants me to download over 3 gb of data, and it's always the same files. it also deleted things, so now many of my cards complain mods are missing. i don't think i disabled anything other than the things disableable through the main loader, like stiletto, autosave etc. when i downloaded files through p2p, it never seemed to registered getting them and tried to make me download them every time. after i got a few through non-p2p it no longer asked about those though.

**Comment by ManlyMarco** [comment] 2023-02-10 15:12
[debug.zip](https://github.com/IllusionMods/KKManager/files/10708782/debug.zip)
Can you reproduce the issue with this build (including downloading the erroneous files and closing KKManager) and send me the resulting KKManager.log file?

**Comment by yarrmateys** [comment] 2023-02-10 15:47
i can't seem to start this copy. it complains about no valid update sources found once i start the updater. kkmanager.log hasn't been generated since 0.20.2

**Comment by ManlyMarco** [comment] 2023-02-10 16:05
My bad, this one should work. [debug2.zip](https://github.com/IllusionMods/KKManager/files/10709208/debug2.zip)

**Comment by yarrmateys** [comment] 2023-02-10 16:59
[StandaloneUpdater.log](https://github.com/IllusionMods/KKManager/files/10709492/StandaloneUpdater.log)
here's the log. i ran it in p2p mode and downloaded the 2.5 gb package, then clicked ok after finishing. trying to run it again made the same package to appear. 
when i downloaded the 1 gb package without p2p mode earlier the updater correctly accepted it as downloaded and didn't show it as available to download anymore.

**Comment by ManlyMarco** [comment] 2023-02-10 17:20
Oh, so it only happens with the stand-alone updater, but the updater inside KKManager works fine?

**Comment by yarrmateys** [comment] 2023-02-10 19:09
seems like it. i tried downloading a 3.59 gb package with it, and on a second check it wasn't there anymore. it also disappeared from the stand alone updater.

**Comment by ManlyMarco** [comment] 2023-02-11 08:19
@yarrmateys Can you check if this build fixes the issue? Also check if closing the updater inside KKManager still works fine and doesn't get stuck.
[debug3.zip](https://github.com/IllusionMods/KKManager/files/10712944/debug3.zip)

**Comment by yarrmateys** [comment] 2023-02-11 15:49
i removed one mod and ran standalone in p2p mode, and it downloaded the file now. after clicking ok it froze for about 30 seconds, but eventually closed. kkmanager's updater does the same.

**Comment by ManlyMarco** [comment] 2023-02-11 17:20
Nice, thanks for testing. I'll put out a release in a bit.

**Closed by ManlyMarco** 2023-02-11 17:20 UTC
Labels: bug, mod updater
