### ISSUE TITLE
Super Slow Downloads

### ISSUE THREAD

**Issue by Elryyyyyyyy** [IllusionMods/KKManager#66] opened 2021-11-06 22:01 UTC
Its a pain to update mods, download is not even 1mb/s.
Could you please fix that ?
![image](https://user-images.githubusercontent.com/93844225/140625017-e9bfd93c-8cc3-429b-8c21-17bf07cf079d.png)

**Comment by Elryyyyyyyy** [comment] 2021-11-06 22:20
It has nothing to do with the amount of users, it cant be that much on your server or youre really cheaping out on the server.

**Comment by Elryyyyyyyy** [comment] 2021-11-06 22:23
Please fix this, just to be fair to your patreons and the users.

**Comment by ManlyMarco** [comment] 2021-11-07 10:26
I think you're severely underestimating the popularity of these games and the amount of data being sent, here's stats from one of the servers
![Clipboard01](https://user-images.githubusercontent.com/39247311/140640449-a707418a-7a2f-4a0b-ba52-5254faf0481d.png)
This is one out of 5 at the moment I believe, upload is pinned at 100% 24/7. To make the speeds twice as fast as they are now you're talking 5 new servers (if you take faster completion times into account then maybe 3). If you want to talk more in depth about the servers feel free to ping one of the maintainers on the IS or KK discord server.

> Its a pain to update mods, download is not even 1mb/s.

During off-peak hours you can easily get 10MBps+ speeds, if stars align you can even get ten times that.
![Clipboard02](https://user-images.githubusercontent.com/39247311/140641171-ce16e3e3-4859-4cd0-95c4-ec733d5f6862.png)

**Comment by ManlyMarco** [comment] 2021-11-07 10:32
Closing as duplicate of #55

**Closed by ManlyMarco** 2021-11-07 10:32 UTC
