### ISSUE TITLE
Unable to update or too slowUnable to update or too slow

### ISSUE THREAD

**Issue by NICENCEiver** [IllusionMods/KKManager#89] opened 2022-10-27 16:21 UTC
This problem has occurred before, but it was solved in the first half of 2022. Now I have changed the game file from 1.21 to 1.23, and this problem occurs again. Even the update is slower than that in 2021. The speed of large files will no longer exceed 50K, and the connection will be disconnected frequently. My current proxy settings are the same as those without proxy settings. I want to know what the problem is, I hope it can be resolved. I have updated it for 3 consecutive days, and it has been updated by about 10GB. Please help me, thank you!

**Comment by ManlyMarco** [comment] 2022-10-28 20:15
This has nothing to do with KKManager itself, the servers are just overloaded.
Duplicate of #55

**Closed by ManlyMarco** 2022-10-28 20:15 UTC
