### ISSUE TITLE
Window Size and off-screen geometry and position

### ISSUE THREAD

**Issue by bytemask** [IllusionMods/KKManager#96] opened 2022-11-29 14:57 UTC
Sometimes, usually after a critical error that causes an application crash, the window geometry becomes corrupted, possibly because kkmanager.config is malformed(?). Need to replicate and collect information and prevent this from happening, possibly via a sanity check (impossible geometries and off-screen coordinates should just be ruled invalid and reset?).

**Comment by ManlyMarco** [comment] 2022-11-29 20:32
It was attempted to be fixed here https://github.com/IllusionMods/KKManager/commit/626bfe522c0217da6733cb21147f07d64cde4391

**Comment by ManlyMarco** [comment] 2022-12-15 08:52
I didn't get any reports related to this since the fix mentioned above, closing until someone can reproduce the issue.

**Closed by ManlyMarco** 2022-12-15 08:52 UTC
Labels: bug
