### ISSUE TITLE
Refresh mod list not get the same result

### ISSUE THREAD

**Issue by jirat-sumitanun** [IllusionMods/KKManager#141] opened 2023-10-27 14:00 UTC
I enable Bleeding Edge so I have downloaded many duplicate mods.
When I check for duplicate guid some mods not showing on the list, even I see duplicate mod inside folder.
And if I click refresh multiple times, the scroll bar not the same height. It's mean some got load and some are not.
Are there any limitation like how many mods can show on the list or the folder with some symbol will not get scan?

I have mod around 8000 mods.

First loading: https://ibb.co/jkKxsQ7
after refresh 2-3 times: https://ibb.co/QbkxNY9

**Comment by ManlyMarco** [comment] 2023-10-31 09:03
Make sure that KKManager has finished loading zipmods, you can see the finish message in the status bar and log window. There should be no limitation to the amount.

**Comment by ManlyMarco** [comment] 2024-04-13 20:30
Closing since I can't reproduce the issue / don't know if it's an issue.

**Closed by ManlyMarco** 2024-04-13 20:30 UTC
